[general]
live_config_reload = true
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
opacity = 1.0


[window.padding]
x = 10

[font]
normal = { family = "Maple Mono NF", style = "Regular" }
bold = { family = "Maple Mono NF", style = "Bold" }
italic = { family = "Maple Mono NF", style = "Italic" }
bold_italic = { family = "Maple Mono NF", style = "Bold Italic" }
size = 13.0

[terminal]
shell = "/bin/zsh"

[cursor]
unfocused_hollow = false

  [cursor.style]
  shape = "Beam"

[env]
TERM = "xterm-256color"

[[keyboard.bindings]]
key = "F11"
action = "ToggleFullscreen"

[[keyboard.bindings]]
key = "V"
mods = "Control"
action = "Paste"

[[keyboard.bindings]]
key = "Up"
mods = "Shift"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "Down"
mods = "Shift"
action = "ScrollPageDown"

[[keyboard.bindings]]
key = "Up"
mods = "Control"
action = "ScrollToTop"
